ttable = int(input('Write a number: '))
print('-' * 15)
print('{} * {:2} = {:>2}'.format(ttable, 1, ttable * 1))
print('{} * {:2} = {}'.format(ttable, 2, ttable * 2))
print('{} * {:2} = {}'.format(ttable, 3, ttable * 3))
print('{} * {:2} = {}'.format(ttable, 4, ttable * 4))
print('{} * {:2} = {}'.format(ttable, 5, ttable * 5))
print('{} * {:2} = {}'.format(ttable, 6, ttable * 6))
print('{} * {:2} = {}'.format(ttable, 7, ttable * 7))
print('{} * {:2} = {}'.format(ttable, 8, ttable * 8))
print('{} * {:2} = {}'.format(ttable, 9, ttable * 9))
print('{} * {:2} = {}'.format(ttable, 10, ttable * 10))
print('-' * 15)