phrase = 'Leonardo César Silva Rodrigues'
print('Your name is {}!'.format(phrase[0:10]))
print('Your name is {}!'.format(phrase[0:9:2]))
print('Your name is {}!'.format(phrase[:7]))
print('Your name is {}!'.format(phrase[1:]))
print('Your name is {}!'.format(phrase[0::2]))
print('Your name is {}!'.format(len(phrase)))
print('Your name is {}!'.format(phrase.count('o')))
print('Your name is {}!'.format(phrase.count('o', 0, 10)))
print('Your name is {}!'.format(phrase.find('do')))
print('Your name is {}!'.format(phrase.find('dro')))
print('Your name is {}!'.format(phrase.replace('Leonardo', 'Leleco')))
print('Your name is {}!'.format(phrase.upper()))
print('Your name is {}!'.format(phrase.lower()))
print('Your name is {}!'.format(phrase.capitalize()))
print('Your name is {}!'.format(phrase.title()))
print('Your name is {}!'.format(phrase.strip()))
print('Your name is {}!'.format(phrase.rstrip()))
print('Your name is {}!'.format(phrase.lstrip()))
print('Your name is {}!'.format(phrase.split()))

